/* SAMBRIX 20.30 — Agenda, disponibilidad y reprogramación */
(function(){
 const A=window.App;if(!A)return;
 const DAYS=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 A.ensureSchedule=function(b){
   b.schedule=b.schedule||{};
   if(!b.schedule.weekly){b.schedule.weekly={};for(let d=0;d<7;d++)b.schedule.weekly[d]={enabled:true,start:A.db.business.open||'09:00',end:A.db.business.close||'18:00',breaks:[]};}
   b.schedule.blocks=b.schedule.blocks||[]; return b.schedule;
 };
 A.professionalWindow=function(barberId,date){
   const b=A.db.barbers.find(x=>x.id===barberId);if(!b)return null;const s=A.ensureSchedule(b),d=new Date(date+'T12:00:00').getDay(),w=s.weekly[d];
   if(!w?.enabled)return null;
   const blocks=(s.blocks||[]).filter(x=>x.date===date).map(x=>({start:x.start||w.start,end:x.end||w.end,allDay:!!x.allDay}));
   if(blocks.some(x=>x.allDay))return null;return {...w,blocks};
 };
 A.slotAvailable=function(barberId,date,time,duration,ignoreId){
   const w=A.professionalWindow(barberId,date);if(!w)return false;const start=A.parseTime(time),end=start+Number(duration||40);
   if(start<A.parseTime(w.start)||end>A.parseTime(w.end))return false;
   if((w.breaks||[]).some(x=>start<A.parseTime(x.end)&&end>A.parseTime(x.start)))return false;
   if((w.blocks||[]).some(x=>start<A.parseTime(x.end)&&end>A.parseTime(x.start)))return false;
   return !(A.db.appointments||[]).some(a=>{if(a.id===ignoreId||a.barberId!==barberId||a.date!==date||['Cancelada','Rechazada'].includes(a.status))return false;const sv=A.db.services.find(x=>x.id===a.serviceId),as=A.parseTime(a.time),ae=as+Number(sv?.duration||40);return start<ae&&end>as;});
 };
 A.availableBarbers=(date,time,duration)=>A.db.barbers.filter(b=>A.slotAvailable(b.id,date,time,duration));
 A.availableSlots=function(barberId,date,serviceId,ignoreId){const sv=A.db.services.find(x=>x.id===serviceId),w=A.professionalWindow(barberId,date);if(!sv||!w)return[];const arr=[];for(let n=A.parseTime(w.start);n+Number(sv.duration||40)<=A.parseTime(w.end);n+=30){const t=A.fmtTime(n);if(A.slotAvailable(barberId,date,t,sv.duration,ignoreId))arr.push(t)}return arr;};

 A.openSchedule=function(id){const b=A.db.barbers.find(x=>x.id===id);if(!b)return;const s=A.ensureSchedule(b);let m=document.getElementById('scheduleModal');if(!m){m=document.createElement('div');m.id='scheduleModal';m.className='modal hidden';document.body.appendChild(m)}
   const tier=window.SaaS?.businessPlanTier?.()||window.SaaS?.planTier?.(A.db.business)||'basic',advanced=tier==='pro'||tier==='premium';
   m.innerHTML=`<div class="modal-card schedule-card"><div class="panel-head"><div><span class="tag">DISPONIBILIDAD</span><h3>${esc(b.name)}</h3></div><button class="btn secondary" onclick="App.closeSchedule()">Cerrar</button></div><p class="muted">Define cuándo este profesional puede recibir reservas.</p><div class="schedule-week">${DAYS.map((name,d)=>{const w=s.weekly[d]||{};return `<div class="schedule-day"><label><input type="checkbox" data-sch-day="${d}" ${w.enabled?'checked':''}> ${name}</label><input type="time" data-sch-start="${d}" value="${w.start||'09:00'}"><span>a</span><input type="time" data-sch-end="${d}" value="${w.end||'18:00'}"><input type="text" data-sch-break="${d}" value="${(w.breaks||[]).map(x=>x.start+'-'+x.end).join(', ')}" placeholder="Descanso 13:00-14:00"></div>`}).join('')}</div>${advanced?`<div class="panel compact-panel"><h3>Bloqueos especiales · PRO+</h3><p class="muted">Vacaciones, permisos o horas que no quieras mostrar al cliente.</p><div class="form-grid"><label>Fecha<input id="schBlockDate" type="date"></label><label>Desde<input id="schBlockStart" type="time"></label><label>Hasta<input id="schBlockEnd" type="time"></label></div><button class="btn secondary" onclick="App.addScheduleBlock('${id}')">+ Bloquear horario</button><div id="schBlockList" class="stack"></div></div>`:`<div class="permission-note"><strong>Horario básico activo.</strong> Los bloqueos especiales por fecha están disponibles desde Pro.</div>`}<div class="actions"><button class="btn primary" onclick="App.saveSchedule('${id}')">Guardar disponibilidad</button></div></div>`;m.classList.remove('hidden');m.classList.add('open');A.renderScheduleBlocks(id);
 };
 A.closeSchedule=()=>{const m=document.getElementById('scheduleModal');if(m){m.classList.add('hidden');m.classList.remove('open')}};
 A.saveSchedule=function(id){const b=A.db.barbers.find(x=>x.id===id);if(!b)return;const s=A.ensureSchedule(b);for(let d=0;d<7;d++){const raw=document.querySelector(`[data-sch-break="${d}"]`)?.value||'';const breaks=raw.split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const [start,end]=x.split('-').map(v=>v.trim());return start&&end?{start,end}:null}).filter(Boolean);s.weekly[d]={enabled:!!document.querySelector(`[data-sch-day="${d}"]`)?.checked,start:document.querySelector(`[data-sch-start="${d}"]`)?.value||'09:00',end:document.querySelector(`[data-sch-end="${d}"]`)?.value||'18:00',breaks};}A.persist();A.toast('Disponibilidad guardada');A.closeSchedule();};
 A.addScheduleBlock=function(id){const b=A.db.barbers.find(x=>x.id===id),date=A.val('schBlockDate'),start=A.val('schBlockStart'),end=A.val('schBlockEnd');if(!b||!date)return A.toast('Selecciona una fecha');const s=A.ensureSchedule(b);s.blocks.push({id:A.uid(),date,start:start||'00:00',end:end||'23:59',allDay:!start&&!end});A.persist();A.renderScheduleBlocks(id);};
 A.removeScheduleBlock=function(bid,id){const b=A.db.barbers.find(x=>x.id===bid);if(!b)return;b.schedule.blocks=b.schedule.blocks.filter(x=>x.id!==id);A.persist();A.renderScheduleBlocks(bid);};
 A.renderScheduleBlocks=function(id){const root=document.getElementById('schBlockList'),b=A.db.barbers.find(x=>x.id===id);if(!root||!b)return;root.innerHTML=(A.ensureSchedule(b).blocks||[]).map(x=>`<div class="row"><div><strong>${x.date}</strong><small>${x.allDay?'Día completo':x.start+' - '+x.end}</small></div><button class="btn danger" onclick="App.removeScheduleBlock('${id}','${x.id}')">Quitar</button></div>`).join('')||'<div class="muted">Sin bloqueos especiales.</div>';};

 const oldRB=A.renderBarbers;A.renderBarbers=function(){oldRB?.();document.querySelectorAll('#barberList .professional-card').forEach((card,i)=>{const b=A.db.barbers[i];if(!b||card.querySelector('.schedule-btn'))return;const actions=card.querySelector('.manage-actions');actions?.insertAdjacentHTML('afterbegin',`<button class="btn secondary schedule-btn" onclick="App.openSchedule('${b.id}')">Horarios</button>`)});};

 A.openReschedule=function(id){const a=A.db.appointments.find(x=>x.id===id);if(!a)return;let m=document.getElementById('rescheduleModal');if(!m){m=document.createElement('div');m.id='rescheduleModal';m.className='modal hidden';document.body.appendChild(m)}m.dataset.appt=id;m.innerHTML=`<div class="modal-card"><div class="panel-head"><div><span class="tag">REPROGRAMAR</span><h3>Elegir nuevo horario</h3></div><button class="btn secondary" onclick="App.closeReschedule()">Cerrar</button></div><div class="form-grid"><label>Fecha<input id="rescheduleDate" type="date" value="${a.date}" onchange="App.renderRescheduleSlots()"></label><label>Profesional<input value="${esc(A.barberName(a.barberId))}" disabled></label></div><p class="muted">Solo se muestran horas realmente disponibles para este profesional.</p><div id="rescheduleSlots" class="slots"></div><input id="rescheduleTime" type="hidden"><div class="actions"><button class="btn primary" onclick="App.submitRescheduleRequest()">Enviar solicitud</button></div></div>`;m.classList.remove('hidden');m.classList.add('open');A.renderRescheduleSlots();};
 A.closeReschedule=()=>{const m=document.getElementById('rescheduleModal');if(m){m.classList.add('hidden');m.classList.remove('open')}};
 A.renderRescheduleSlots=function(){const m=document.getElementById('rescheduleModal'),a=A.db.appointments.find(x=>x.id===m?.dataset.appt);if(!a)return;const date=A.val('rescheduleDate'),slots=A.availableSlots(a.barberId,date,a.serviceId,a.id),root=document.getElementById('rescheduleSlots');root.innerHTML=slots.map(t=>`<button type="button" class="slot" onclick="document.getElementById('rescheduleTime').value='${t}';document.querySelectorAll('#rescheduleSlots .slot').forEach(x=>x.classList.remove('selected'));this.classList.add('selected')">${t}</button>`).join('')||'<div class="muted">No hay horas disponibles ese día.</div>';};
 A.submitRescheduleRequest=function(){const m=document.getElementById('rescheduleModal'),a=A.db.appointments.find(x=>x.id===m?.dataset.appt),date=A.val('rescheduleDate'),time=A.val('rescheduleTime');if(!a||!date||!time)return A.toast('Selecciona una hora disponible');if(!A.slotAvailable(a.barberId,date,time,A.db.services.find(x=>x.id===a.serviceId)?.duration||40,a.id))return A.toast('Ese horario acaba de ocuparse. Elige otro.');const c=A.db.clients.find(x=>x.id===a.clientId);A.db.clientRequests=A.db.clientRequests||[];A.db.clientRequests.push({id:A.uid(),type:'reschedule',appointmentId:a.id,status:'Pendiente',clientId:a.clientId,clientName:c?.name||'Cliente',phone:c?.phone||'',oldDate:a.date,oldTime:a.time,newDate:date,newTime:time,createdAt:new Date().toISOString()});A.addClientActivity?.('Solicitud de reprogramación',`${c?.name||'Cliente'} · ${a.date} ${a.time} → ${date} ${time}`,c?.phone||'');A.persist();A.closeReschedule();A.lookupClientAppointments();A.renderClientRequestAdmin?.();A.toast('Solicitud enviada al administrador');};
 const oldReq=A.requestAppointmentChange;A.requestAppointmentChange=function(id,action){if(action==='reschedule')return A.openReschedule(id);return oldReq?.(id,action);};

 const oldLookup=A.lookupClientAppointments;A.lookupClientAppointments=function(){oldLookup?.();const phone=A.val('clientLookupPhone').replace(/\D/g,''),c=A.db.clients.find(x=>(x.phone||'').replace(/\D/g,'')===phone);if(!c)return;const root=A.byId('clientAppointmentsList');root.innerHTML=A.db.appointments.filter(a=>a.clientId===c.id).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).map(a=>{const req=(A.db.clientRequests||[]).filter(r=>r.appointmentId===a.id&&r.type==='reschedule').sort((x,y)=>(y.createdAt||'').localeCompare(x.createdAt||''))[0];return `<div class="row"><div><strong>${a.date} ${a.time}</strong><small>${A.serviceName(a.serviceId)} · ${A.barberName(a.barberId)} · ${a.status}${req?` · Reprogramación: ${req.status}${req.status==='Pendiente'?` → ${req.newDate} ${req.newTime}`:''}`:''}</small></div>${['Pendiente','Confirmada'].includes(a.status)&&!req?.status?.includes('Pendiente')?`<div class="request-actions"><button class="btn secondary" onclick="App.openReschedule('${a.id}')">Reprogramar</button><button class="btn danger" onclick="App.requestAppointmentChange('${a.id}','cancel')">Cancelar</button></div>`:''}</div>`}).join('')||'<div class="muted">No tienes citas registradas.</div>';};

 A.renderAgendaRequests=function(){let root=document.getElementById('agendaRequests20');const page=document.getElementById('citas');if(!page)return;if(!root){root=document.createElement('div');root.id='agendaRequests20';root.className='panel';page.insertBefore(root,document.getElementById('appointmentList'));}const pending=(A.db.clientRequests||[]).filter(r=>r.status==='Pendiente');root.innerHTML=`<div class="panel-head"><div><span class="tag">SOLICITUDES DEL CLIENTE</span><h3>Reprogramaciones y cancelaciones</h3></div><strong>${pending.length} pendientes</strong></div>${pending.map(r=>`<div class="row"><div><strong>${r.type==='reschedule'?'Reprogramar':'Cancelar'} · ${esc(r.clientName)}</strong><small>${r.oldDate} ${r.oldTime}${r.type==='reschedule'?` → ${r.newDate} ${r.newTime}`:''}</small></div><div class="request-actions"><button class="btn primary" onclick="App.approveClientRequest('${r.id}')">Aprobar</button><button class="btn danger" onclick="App.rejectClientRequest('${r.id}')">Rechazar</button></div></div>`).join('')||'<div class="muted">No hay solicitudes pendientes.</div>'}`;};
 const oldRA=A.renderAppointments;A.renderAppointments=function(){const r=oldRA?.();A.renderAgendaRequests();return r;};
 const oldApprove=A.approveClientRequest;A.approveClientRequest=function(id){oldApprove?.(id);A.renderAgendaRequests();A.lookupClientAppointments?.();};const oldReject=A.rejectClientRequest;A.rejectClientRequest=function(id){oldReject?.(id);A.renderAgendaRequests();A.lookupClientAppointments?.();};

 // Edición dedicada: funciona también después de finalizar.
 A.editAppointment=function(id){const a=A.db.appointments.find(x=>x.id===id);if(!a)return;let m=document.getElementById('apptEdit2030');if(!m){m=document.createElement('div');m.id='apptEdit2030';m.className='modal hidden';document.body.appendChild(m)}m.dataset.id=id;m.innerHTML=`<div class="modal-card"><div class="panel-head"><div><span class="tag">CITA</span><h3>Editar cita${a.status==='Finalizada'?' finalizada':''}</h3></div><button class="btn secondary" onclick="App.closeApptEdit2030()">Cerrar</button></div><div class="form-grid"><label>Cliente<select id="e2030Client">${A.db.clients.map(x=>`<option value="${x.id}" ${x.id===a.clientId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Profesional<select id="e2030Barber">${A.db.barbers.map(x=>`<option value="${x.id}" ${x.id===a.barberId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Servicio<select id="e2030Service">${A.db.services.map(x=>`<option value="${x.id}" ${x.id===a.serviceId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Fecha<input id="e2030Date" type="date" value="${a.date}"></label><label>Hora<input id="e2030Time" type="time" value="${a.time}"></label><label>Estado<select id="e2030Status">${['Pendiente','Confirmada','Finalizada','Cancelada','Rechazada'].map(x=>`<option ${x===a.status?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Observaciones<textarea id="e2030Note">${esc(a.note||'')}</textarea></label></div>${a.status==='Finalizada'?'<div class="permission-note">Esta cita ya fue finalizada. Puedes corregir sus datos; SAMBRIX conservará la marca de modificación.</div>':''}<div class="actions"><button class="btn primary" onclick="App.saveApptEdit2030()">Guardar cambios</button></div></div>`;m.classList.remove('hidden');m.classList.add('open');};
 A.closeApptEdit2030=()=>{const m=document.getElementById('apptEdit2030');if(m){m.classList.add('hidden');m.classList.remove('open')}};
 A.saveApptEdit2030=function(){const m=document.getElementById('apptEdit2030'),a=A.db.appointments.find(x=>x.id===m?.dataset.id);if(!a)return;const barberId=A.val('e2030Barber'),serviceId=A.val('e2030Service'),date=A.val('e2030Date'),time=A.val('e2030Time'),sv=A.db.services.find(x=>x.id===serviceId);if(!A.slotAvailable(barberId,date,time,sv?.duration||40,a.id)&&!['Cancelada','Rechazada'].includes(A.val('e2030Status')))return A.toast('Ese horario no está disponible para el profesional');Object.assign(a,{clientId:A.val('e2030Client'),barberId,serviceId,date,time,status:A.val('e2030Status'),note:A.val('e2030Note'),editedAt:new Date().toISOString()});A.persist();A.closeApptEdit2030();A.toast('Cita actualizada');};

 const oldRenderClientSlots=A.renderClientSlots;A.renderClientSlots=function(){return oldRenderClientSlots?.();};
 setTimeout(()=>{A.renderBarbers?.();A.renderAppointments?.();},100);
})();
