App.defaultSchedule=function(){
  return {1:{active:true,start:"09:00",end:"18:00"},2:{active:true,start:"09:00",end:"18:00"},3:{active:true,start:"09:00",end:"18:00"},4:{active:true,start:"09:00",end:"18:00"},5:{active:true,start:"09:00",end:"18:00"},6:{active:true,start:"09:00",end:"16:00"},0:{active:false,start:"09:00",end:"14:00"}};
};
App.ensureStaff=function(){
  App.db.employees=App.db.employees||[];App.db.attendance=App.db.attendance||[];
  App.db.employees.forEach(e=>{if(String(e.pin||"")==="1234")e.pin=""});
  App.db.barbers.forEach(b=>{if(!App.db.employees.some(e=>e.barberId===b.id))App.db.employees.push({id:App.uid(),barberId:b.id,name:b.name,role:(App.businessVocabulary?.().staffRole||"Profesional"),phone:b.phone||"",pin:"",serviceCommission:Number(b.commission||40),productCommission:0,monthlyGoal:500,weeklyGoal:125,active:true,photo:App.db.business.clientApp.barberPhotos?.[b.id]||"",schedule:App.defaultSchedule()})});
};
App.saveEmployee=function(){
  const id=App.val("employeeEditId");
  const data={name:App.val("employeeName"),role:App.val("employeeRole"),phone:App.val("employeePhone"),pin:String(App.val("employeePin")||"").replace(/\D/g,"").slice(0,6),serviceCommission:Number(App.val("employeeServiceCommission")||0),productCommission:Number(App.val("employeeProductCommission")||0),monthlyGoal:Number(App.val("employeeMonthlyGoal")||0),weeklyGoal:Number(App.val("employeeMonthlyGoal")||0)/4,active:App.val("employeeActive")==="true"};
  if(!data.name)return App.toast("Escribe el nombre");
  if(data.pin&&!/^\d{6}$/.test(data.pin))return App.toast("El PIN de asistencia debe tener 6 números");
  const finish=photo=>{if(id){const e=App.db.employees.find(x=>x.id===id);Object.assign(e,data);if(photo)e.photo=photo}else App.db.employees.push({id:App.uid(),...data,photo:photo||"",schedule:App.defaultSchedule()});App.persist();App.byId("employeeForm").classList.add("hidden");App.renderAll();App.toast("Empleado guardado")};
  const file=App.byId("employeePhoto")?.files?.[0];if(file){const r=new FileReader();r.onload=()=>finish(r.result);r.readAsDataURL(file)}else finish("");
};
App.editEmployee=function(id){const e=App.db.employees.find(x=>x.id===id);if(!e)return;App.byId("employeeEditId").value=e.id;App.byId("employeeName").value=e.name||"";App.byId("employeeRole").value=e.role||"Profesional";App.byId("employeePhone").value=e.phone||"";App.byId("employeePin").value=e.pin||"";App.byId("employeeServiceCommission").value=e.serviceCommission||0;App.byId("employeeProductCommission").value=e.productCommission||0;App.byId("employeeMonthlyGoal").value=e.monthlyGoal||0;App.byId("employeeActive").value=String(e.active!==false);App.byId("employeeForm").classList.remove("hidden")};
App.renderStaff=function(){
  App.ensureStaff();const box=App.byId("employeeList");if(!box)return;box.innerHTML="";
  App.db.employees.forEach(e=>{const c=document.createElement("article");c.className="card";c.innerHTML=`${e.photo?`<img src="${e.photo}" class="image-preview square">`:""}<h3>${e.name}</h3><small>${e.role||""} · ${e.phone||""}</small><div class="big">${e.active!==false?"Activo":"Inactivo"}</div><small>Servicios ${e.serviceCommission||0}% · Productos ${e.productCommission||0}%</small><div class="manage-actions"><button class="btn edit" onclick="App.editEmployee('${e.id}')">Editar</button><button class="btn secondary" onclick="App.openEmployeeSchedule('${e.id}')">Horario</button></div>`;box.appendChild(c)});
};
App.openEmployeeSchedule=function(id){const e=App.db.employees.find(x=>x.id===id);if(!e)return;App.byId("scheduleEmployeeId").value=id;App.byId("scheduleEmployeeName").textContent=e.name;e.schedule=e.schedule||App.defaultSchedule();const days=[[1,"Lunes"],[2,"Martes"],[3,"Miércoles"],[4,"Jueves"],[5,"Viernes"],[6,"Sábado"],[0,"Domingo"]];App.byId("scheduleEditor").innerHTML=days.map(([n,name])=>`<div class="row"><label style="min-width:120px"><input type="checkbox" data-day-active="${n}" ${e.schedule[n]?.active?"checked":""}> ${name}</label><input type="time" data-day-start="${n}" value="${e.schedule[n]?.start||"09:00"}"><input type="time" data-day-end="${n}" value="${e.schedule[n]?.end||"18:00"}"></div>`).join("");App.byId("scheduleModal").classList.remove("hidden")};
App.saveEmployeeSchedule=function(){const e=App.db.employees.find(x=>x.id===App.val("scheduleEmployeeId"));if(!e)return;e.schedule=e.schedule||{};[0,1,2,3,4,5,6].forEach(n=>{e.schedule[n]={active:!!document.querySelector(`[data-day-active="${n}"]`)?.checked,start:document.querySelector(`[data-day-start="${n}"]`)?.value||"09:00",end:document.querySelector(`[data-day-end="${n}"]`)?.value||"18:00"}});App.persist();App.byId("scheduleModal").classList.add("hidden");App.renderAll();App.toast("Horario guardado")};
App.renderAttendance=function(){App.ensureStaff();const sel=App.byId("attendanceEmployee");if(sel){const current=sel.value;sel.innerHTML=App.db.employees.filter(e=>e.active!==false).map(e=>`<option value="${e.id}">${e.name}</option>`).join("");if([...sel.options].some(o=>o.value===current))sel.value=current}const list=App.byId("attendanceList");if(list)list.innerHTML=[...App.db.attendance].reverse().slice(0,80).map(a=>{const e=App.db.employees.find(x=>x.id===a.employeeId);return `<div class="row"><div><strong>${e?.name||"Empleado"}</strong><small>${a.date} · Entrada ${a.in||"—"} · Salida ${a.out||"—"}</small></div><span>${a.late?"Retardo":""}</span></div>`}).join("")||"<small>Sin marcaciones</small>"};
App.scheduleForDate=function(e,date){const d=new Date(date+"T12:00:00").getDay();return (e.schedule||App.defaultSchedule())[d]};
App.clockIn=function(){const e=App.db.employees.find(x=>x.id===App.val("attendanceEmployee"));if(!e)return;if(!/^\d{6}$/.test(String(e.pin||"")))return App.toast("Este empleado debe configurar un PIN de asistencia de 6 dígitos");if(String(e.pin)!==String(App.val("attendancePin")))return App.toast("PIN incorrecto");if(App.db.attendance.some(a=>a.employeeId===e.id&&a.date===App.today()&&!a.out))return App.toast("Ya existe una entrada abierta");const time=new Date().toTimeString().slice(0,5),sch=App.scheduleForDate(e,App.today());const late=!!(sch?.active&&App.parseHours(time)>App.parseHours(sch.start)+5);App.db.attendance.push({id:App.uid(),employeeId:e.id,date:App.today(),in:time,out:"",late});App.logAction("Entrada marcada","Asistencia",`${e.name} · ${time}`);localStorage.setItem(App.KEY,JSON.stringify(App.db));App.renderAll();App.toast(late?"Entrada registrada con retardo":"Entrada registrada")};
App.clockOut=function(){const e=App.db.employees.find(x=>x.id===App.val("attendanceEmployee"));if(!e)return;if(!/^\d{6}$/.test(String(e.pin||"")))return App.toast("Este empleado debe configurar un PIN de asistencia de 6 dígitos");if(String(e.pin)!==String(App.val("attendancePin")))return App.toast("PIN incorrecto");const a=[...App.db.attendance].reverse().find(x=>x.employeeId===e.id&&x.date===App.today()&&!x.out);if(!a)return App.toast("No hay entrada abierta");a.out=new Date().toTimeString().slice(0,5);App.logAction("Salida marcada","Asistencia",`${e.name} · ${a.out}`);localStorage.setItem(App.KEY,JSON.stringify(App.db));App.renderAll();App.toast("Salida registrada")};
